version: '3.8'

networks:

  itmo:

volumes:
  pgdata:

services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Web3
    networks:
      - itmo


  wildfly:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
      - "9990:9990"
    environment:
      - POSTGRESQL_USER=admin
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_DATABASE=Web3
    depends_on:
      - database
    networks:
      - itmo